trigger_email_template = """\
<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <style>
        .container {
            font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
            max-width: 600px;
            margin: 0 auto;
            border: 1px solid #e0e0e0;
            border-radius: 8px;
            overflow: hidden;
        }

        .header {
            background-color: #1a1a1a;
            color: #ffffff;
            padding: 20px;
            text-align: center;
        }

        .content {
            padding: 30px;
            line-height: 1.6;
            color: #333333;
        }

        .user-body {
            background-color: #f9f9f9;
            border-left: 4px solid #007bff;
            padding: 15px;
            margin: 20px 0;
            border-radius: 4px;
        }

        .footer {
            background-color: #f4f4f4;
            color: #777777;
            padding: 15px;
            text-align: center;
            font-size: 12px;
        }

        .badge {
            background-color: #007bff;
            color: white;
            padding: 4px 8px;
            border-radius: 12px;
            font-size: 11px;
            text-transform: uppercase;
        }
    </style>
</head>

<body>
    <div class="container">
        <div class="header">
            <h1 style="margin:0; font-size: 24px;">SyncraFlow</h1>
        </div>
        <div class="content">
            <p>Hello,</p>
            <p>An action has been triggered via your workflow <span class="badge">{{workflow_name}}</span>.</p>

            <div class="user-body">
                {{user_content}}
            </div>
        </div>
        <div class="footer">
            <p>Sent by <strong>SyncraFlow Engine</strong>.</p>
            <p><a href="https://syncraflow.io" style="color: #007bff; text-decoration: none;">Visit the dashboard</a></p>
        </div>
    </div>
</body>

</html>
"""


email_step_template = """\
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <style>
        .email-wrapper { background-color: #f6f9fc; padding: 20px; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif; }
        .email-card { max-width: 580px; margin: 0 auto; background: #ffffff; border-radius: 12px; overflow: hidden; box-shadow: 0 4px 12px rgba(0,0,0,0.08); }
        .email-header { background-color: #007bff; padding: 40px 20px; text-align: center; color: #ffffff; }
        .email-body { padding: 40px 30px; color: #444444; line-height: 1.6; }
        .data-list { margin: 25px 0; border-top: 1px solid #eeeeee; }
        .data-item { padding: 12px 0; border-bottom: 1px solid #eeeeee; display: block; }
        .data-label { font-weight: 600; color: #8898aa; font-size: 13px; text-transform: uppercase; letter-spacing: 1px; }
        .data-value { display: block; color: #32325d; font-size: 16px; margin-top: 4px; }
        .cta-container { text-align: center; margin-top: 30px; }
        .cta-button { background-color: #24b47e; color: #ffffff; padding: 14px 28px; text-decoration: none; border-radius: 6px; font-weight: 600; display: inline-block; }
        .email-footer { text-align: center; padding: 25px; font-size: 12px; color: #8898aa; }
    </style>
</head>
<body>
    <div class="email-wrapper">
        <div class="email-card">
            <div class="email-header">
                <h1 style="margin: 0; font-size: 24px;">{{business_name}}</h1>
            </div>
            <div class="email-body">
                <h2 style="margin-top: 0; color: #32325d;">{{title}}</h2>

                <div class="data-list">
                    {{details_blocks}}
                </div>


                {{action_button}}

            </div>
            <div class="email-footer">
                <p>Powered by <strong>SyncraFlow</strong></p>
                <p>This automated message was generated by a secure workflow..</p>
            </div>
        </div>
    </div>
</body>
</html>
"""


def get_trigger_email_template(user_content: str, workflow_name: str):
    return trigger_email_template.replace("{{user_content}}", user_content).replace("{{workflow_name}}", workflow_name)


def get_email_step_template(business_name: str, title: str,  details_blocks: str, action_button: str):
    template = email_step_template.replace("{{business_name}}", business_name)
    template = template.replace("{{title}}", title)
    template = template.replace("{{details_blocks}}", details_blocks)
    template = template.replace("{{action_button}}", action_button)

    return template


def get_action_button_template(action_url: str, action_text: str):
    if not action_url or not action_text:
        return ""
    return f"""<div class="cta-container">
    <a href="{action_url}" class="cta-button">{action_text}</a>
    </div>
    """


if __name__ == "__main__":
    action_button = get_action_button_template(
        "https://syncraflow.io/dashboard", "View Dashboard")

    print(action_button)
